execute:
  - i:1
  - s:""
  - while("i < 100")
  -   if("i % 5 is 0 and i % 3 is 0")
  -     s += "FizzBuzz"
  -   else("i % 3 is 0")
  -     s += "Fizz"
  -   else("i % 5 is 0")
  -     s += "Buzz"
  -   end_if
  - end_while